### ISSUE TITLE
How to redirect root /

### ISSUE THREAD

**Issue by ubergesundheit** [willnorris/gum#1]
First of all: Thanks for this really nice piece of software! Usage is very straightforward and it does what it should.

I have just one question: How do I configure the root to redirect ?

**Comment by willnorris** [comment]
hmm, good question... currently it doesn't seem that you can.  I can look into adding support for that, but would like to better understand what you're trying to do.  Are you just wanting to redirect all paths to a single destination?  If so, doing that with an Apache or Nginx config would certainly be simpler.  But I suspect maybe that's not exactly what you're doing?

**Comment by ubergesundheit** [comment]
Hi,

I am using similar to you, as a personal url shortener.. I just need the ability to redirect the / route to anything.

Redirection for all paths that dont have a redirect is another thing which would be a good thing. Or the ability to deliver a html page, but with a 404 status header

I would use an Apache or Nginx, but I don't have own webspace or a server. My Instance of gum is currently running in a Docker container on giantswarm.

Cheers

**Comment by willnorris** [comment]
hmph... so this currently isn't possible.  I'll have to think a little bit about the cleanest way to handle this, as it will require a bit of refactoring.  But I totally agree that it's something that should be supported one way or another.
